# secretGenerator:
# - name: mysql-pass
#   literals:
#   - password=password
# resources:
#   - ./mysql/mysql.yaml
#   - ./wordpress/wordpress.yaml
#   - ./phpmyadmin/phpmyadmin.yaml

---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: mysql-pass
# type: Opaque
# data:
#   root-password: c3VwZXItc2VjcmV0LXBhc3N3b3Jk

# apiVersion: v1
# kind: Secret
# metadata:
#   name: mysql-pass
# type: Opaque
# stringData:
# #phpmyadmin-secrets
#   PMA_HOST: mysql
#   PMA_PORT: "3306"
#   MYSQL_ROOT_PASSWORD: admin
# #mysql-secrets
#   MYSQL_ROOT_PASSWORD: admin
#   MYSQL_USER_NAME: admin
#   MYSQL_USER_PASSWORD: admin
#   MYSQL_DB_NAME: wordpress
# #wordpress-secrets
#   WORDPRESS_DB_HOST: mysql
#   WORDPRESS_DB_USER: admin
#   WORDPRESS_DB_PASSWORD: admin
#   WORDPRESS_DB_NAME: wordpress

apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
type: Opaque
stringData:
  dbname: wordpress
  password: admin
  dbuser: admin
  dbpass: admin