apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
stringData:
# #phpmyadmin-secrets
#   PMA_HOST: mysql
#   PMA_PORT: "3306"
#   MYSQL_ROOT_PASSWORD: admin
# #mysql-secrets
#   MYSQL_ROOT_PASSWORD: admin
  MYSQL_USER: lbisscho
  MYSQL_PASSWORD: password
  INFLUXDB_DATABASE: local_monitoring
  INFLUXDB_USERNAME: root
  INFLUXDB_PASSWORD: root123
  INFLUXDB_HOST: influxdb
  INFLUXDB_DB: local_monitoring
  INFLUXDB_URL: http://influxdb:8086
  INFLUXDB_USER: root
  INFLUXDB_USER_PASSWORD: root1234
  GF_SECURITY_ADMIN_USER: admin
  GF_SECURITY_ADMIN_PASSWORD: admin123
#   MYSQL_DB_NAME: wordpress
# #wordpress-secrets
#   WORDPRESS_DB_HOST: mysql
#   WORDPRESS_DB_USER: admin
#   WORDPRESS_DB_PASSWORD: admin
#   WORDPRESS_DB_NAME: wordpress
  # dbname: wordpress
  password: password
  # dbuser: admin
  # dbpass: admin