# apiVersion: v1
# kind: Service
# metadata:
#   annotations:
#     metallb.universe.tf/allow-shared-ip: shared
#   name: grafana
#   labels:
#     app: grafana
# spec:
#   ports:
#     - port: 3000
#   selector:
#     app: grafana
#     tier: frontend
#   type: LoadBalancer
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: grafana
#   labels:
#     app: grafana
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: grafana
#   template:
#     metadata:
#       labels:
#         app: grafana
#     spec:
#       containers:
#       - name: grafana
#         image: grafana
#         imagePullPolicy: Never
#         ports:
#         - containerPort: 3000
#           name: grafana
#           protocol: TCP

apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: grafana
  labels:
    app: grafana
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: grafana
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana
        imagePullPolicy: Never
        ports:
        - containerPort: 3000

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   creationTimestamp: null
#   labels:
#     app: grafana
#   name: grafana
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: grafana
#   strategy: {}
#   template:
#     metadata:
#       creationTimestamp: null
#       labels:
#         app: grafana
#     spec:
#       containers:
#       - image: grafana
#         name: grafana
#         imagePullPolicy: Never
#         ports:
#         - containerPort: 3000
#         env:
#         - name: GF_SECURITY_ADMIN_USER
#           value: lbisscho
#         - name: GF_SECURITY_ADMIN_PASSWORD
#           value: password
#         volumeMounts:
#         - name: provisioning
#           mountPath: /usr/share/grafana/conf/provisioning
#       volumes:
#       - name: provisioning
#         configMap:
#           name: grafana-config
#           items:
#           - key: dashboards.yml
#             path: dashboards/dashboards.yml
#           - key: datasources.yml
#             path: datasources/datasources.yml
# status: {}
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: grafana-config
# data:
#   datasources.yml: |
#     apiVersion: 1
#     datasources:
#     - name: InfluxDB
#       type: influxdb
#       access: proxy
#       database: influxdb
#       isDefault: true
#       user: lbisscho
#       password: password
#       url: http://influxdb:8086
#   dashboards.yml: |
#     apiVersion: 1
#     providers:
#     - name: 'influxdb'
#       orgId: 1
#       folder: ''
#       folderUid: ''
#       type: file
#       disableDeletion: false
#       editable: true
#       updateIntervalSeconds: 10
#       allowUiUpdates: true
#       options:
#         path: /usr/share/grafana/public/dashboards