apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.99.200-192.168.99.200
# IP for home 192.168.99.100
# Ip for Codam 185.61.55.68
#dig +short myip.opendns.com @resolver1.opendns.com
      