apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
  - name: ssh
    port: 22
    targetPort: 22
  selector:
    app: myappp
    name: nginx
#document start
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  template:
    metadata:
      name: nginx
      labels:
        app: myapp
        name: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: Never
  replicas: 1
  selector:
    matchLabels:
      app: myapp
      name: nginx
